-- ============================================================================
-- Migration 046: synthetic shortage flag (audit FINDING-D2-08)
-- ============================================================================
-- Closes audit FINDING-D2-08. recall_linker._maybe_auto_create_shortage()
-- (backend/scrapers/recall_linker.py:158) auto-creates a shortage_events
-- row with severity='high' whenever a Class I recall lands without a
-- matching active shortage. The drug-resolver runs through
-- _find_or_create_drug, so a recall title that doesn't parse cleanly
-- COULD auto-create a phantom drug + phantom high-severity shortage.
-- The _looks_like_drug_name guard at base_recall_scraper.py:59 mitigates
-- this but isn't bulletproof — a single regulator-feed glitch can leak
-- a fake high-severity shortage into chat answers, persona-page previews,
-- and the public freshness dashboard.
--
-- This migration:
--   • Adds shortage_events.synthetic BOOLEAN DEFAULT FALSE
--   • Adds a partial index for cheap exclude-synthetic filtering on the
--     public-facing queries (the hot path; we never want to show a
--     synthetic shortage as fact)
--   • Adds a COMMENT explaining the lifecycle so future agents understand
--     the safety boundary
--
-- All existing rows get synthetic=false. Future auto-creates (commit
-- pending) set it to true. Frontend filters synthetic out of preview
-- helpers and chat tools; admin surfaces can opt-in to see them.
--
-- Idempotent + reversible (DROP COLUMN). No data movement.
-- ============================================================================

ALTER TABLE shortage_events
  ADD COLUMN IF NOT EXISTS synthetic BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN shortage_events.synthetic IS
  'TRUE when this row was auto-generated by recall_linker from a Class I recall (vs. ingested directly from a regulator''s shortage feed). Synthetic rows MUST be linked to a recall in recall_shortage_links — they exist to give downstream users an early-warning signal, not as authoritative shortage data. Public-facing queries (search, persona preview, chat list_active_shortages) should filter WHERE NOT synthetic; admin surfaces and the recall-traceability UI can opt in to see them. Closes audit FINDING-D2-08.';

-- Partial index — most queries will use `WHERE NOT synthetic`, and the
-- minority of synthetic rows are cheap to scan when explicitly requested.
CREATE INDEX IF NOT EXISTS idx_shortage_events_non_synthetic
  ON shortage_events (last_verified_at DESC)
  WHERE synthetic = FALSE
    AND status IN ('active', 'anticipated');

-- ── Verification (post-apply) ────────────────────────────────────────────
-- Confirm the column exists with the expected default:
--   SELECT column_name, data_type, column_default, is_nullable
--   FROM information_schema.columns
--   WHERE table_name='shortage_events' AND column_name='synthetic';
-- Expected: synthetic | boolean | false | NO
--
-- Confirm no existing rows got accidentally flagged:
--   SELECT COUNT(*) FROM shortage_events WHERE synthetic = TRUE;
-- Expected: 0 (all existing rows are real regulator-feed shortages).
