"""
ANSM France Medicine Availability Scraper
──────────────────────────────────────────
Source:  Agence nationale de sécurité du médicament et des produits de santé
URL:     https://ansm.sante.fr/disponibilites-des-produits-de-sante/medicaments

Data source (confirmed 2026-06-03):
    ANSM publishes a live listing of MITM (Médicaments d'Intérêt Thérapeutique
    Majeur — critical medicines) *currently* in shortage / supply tension /
    recently resolved.  The page is server-side rendered; no JS is needed.

    Scope note — why this is ~267 rows, not "1,000+":
        This is the *live open-situations* view: it lists only situations that
        are currently ongoing or very recently closed.  It is NOT capped or
        paginated — the HTML table and the export both return the identical
        complete set (verified 2026-06-03: HTML had exactly 267 tr[data-href]
        rows, export had 267 data rows; ?page=/?historique= params do not widen
        it).  The "1,000+" figure people expect is the *annual cumulative*
        declaration count from a different source — the data.ansm.sante.fr
        transparency base (TrustMed): 1,076 ruptures + 2,733 risques = 3,809
        declarations for 2024.  That base is a yearly snapshot (refreshed each
        April) behind a Next.js dashboard with no clean CSV/API, so it is NOT a
        substitute for this live feed.  For live status, ~267 is the full set.

    Preferred source — the export endpoint:
        /disponibilites-des-produits-de-sante/medicaments/export
    Despite the filename, this returns a BINARY .xls (OLE2/BIFF8, generated by
    PhpSpreadsheet — Content-Type: application/vnd.ms-excel), NOT CSV.  It is
    parsed with xlrd (ignore_workbook_corruption=True — the file is a slightly
    non-standard CDF that trips xlrd's strict validation).  It carries 9 richly
    structured columns the HTML table does NOT expose:

        Titre | Date de création | Date de mise à jour |
        Date de début de situation | Date de remise à disposition |
        Statut | Produit(s) de santé | Domaine(s) médical(aux) | URL de la page

    The export is strongly preferred over HTML because:
      * "Date de début de situation" is a STABLE start date.  The HTML table's
        visible date column is actually "Date de mise à jour" (last-updated),
        which changes on every ANSM edit.  Since start_date is part of the MD5
        shortage_id dedup key, scraping the update date mints a new id on every
        edit → duplicate churn.  The export's début date is dedup-stable.
      * "Date de remise à disposition" gives a real resolution/end date.
      * "Domaine(s) médical(aux)" gives the therapeutic area (Cardiologie,
        Infectiologie, Oncologie, …) — preserved in raw_data + folded into notes.
      * Status is read from a dedicated column, not inferred from CSS classes.

    The full French row is preserved verbatim in raw_record for audit; the
    French→English normalization (status, reason) runs on top of it.

    Fallback chain: binary .xls → CSV (if ANSM ever switches) → HTML scrape.

HTML table row structure (tr[data-href] rows):
    Each <tr> has a data-href="/disponibilites-des-produits-de-sante/medicaments/{slug}"
    Cells:
        [0]: Dénomination — brand / specialty name
             Often contains INN in parentheses at the end:
             "AZACTAM 1g, poudre pour usage parentéral [aztréonam]"
             → INN extracted via regex: text in [...] or (...)
        [1]: Statut — supply status (CSS class "text-danger" for Rupture)
    The INN also commonly appears as the last word(s) of the URL slug.

Status vocabulary:
    Rupture de stock             → active
    Tension d'approvisionnement  → anticipated
    Arrêt de commercialisation   → resolved  (discontinued)
    Remise à disposition         → resolved
    Normalisé                    → resolved

Data source UUID:  10000000-0000-0000-0000-000000000007  (ANSM, FR)
Country:           France
Country code:      FR
"""

from __future__ import annotations

import csv
import io
import re
from datetime import datetime, timezone

from bs4 import BeautifulSoup
from dateutil import parser as dtparser

from backend.scrapers.base_scraper import BaseScraper


class ANSMScraper(BaseScraper):
    """Scraper for ANSM France medicine availability / shortage list."""

    SOURCE_ID:    str = "10000000-0000-0000-0000-000000000007"
    SOURCE_NAME:  str = "Agence nationale de sécurité du médicament — Disponibilité"
    BASE_URL:     str = "https://ansm.sante.fr"
    LIST_URL:     str = "https://ansm.sante.fr/disponibilites-des-produits-de-sante/medicaments"
    EXPORT_URL:   str = "https://ansm.sante.fr/disponibilites-des-produits-de-sante/medicaments/export"
    COUNTRY:      str = "France"
    COUNTRY_CODE: str = "FR"

    RATE_LIMIT_DELAY: float = 1.5

    # French status → internal status
    _STATUS_MAP: dict[str, str] = {
        "rupture de stock":             "active",
        "rupture":                      "active",
        "tension d'approvisionnement":  "anticipated",
        "tension":                      "anticipated",
        "arrêt de commercialisation":   "resolved",
        "arret de commercialisation":   "resolved",
        "remise à disposition":         "resolved",
        "remise a disposition":         "resolved",
        "normalisé":                    "resolved",
        "normalise":                    "resolved",
        "disponible":                   "resolved",
    }

    # French cause vocabulary → reason_category
    _REASON_MAP: dict[str, str] = {
        "production":           "manufacturing_issue",
        "fabrication":          "manufacturing_issue",
        "qualité":              "manufacturing_issue",
        "qualite":              "manufacturing_issue",
        "matière première":     "raw_material",
        "matiere premiere":     "raw_material",
        "demande":              "demand_surge",
        "distribution":         "supply_chain",
        "approvisionnement":    "supply_chain",
        "arrêt":                "discontinuation",
        "arret":                "discontinuation",
        "commercialisation":    "discontinuation",
        "réglementaire":        "regulatory_action",
        "reglementaire":        "regulatory_action",
    }

    # Regex to extract INN from bracket notation: "[aztréonam]" or "(aztréonam)"
    # Square-bracket form is tried first and allows nested parentheses inside.
    _RE_INN_SQUARE = re.compile(r'\[([^\]]+)\]')
    _RE_INN_PARENS = re.compile(r'\(([a-zàâäéèêëîïôùûü /,\-]+)\)', re.IGNORECASE)

    # ─────────────────────────────────────────────────────────────────────────
    # fetch()
    # ─────────────────────────────────────────────────────────────────────────

    # OLE2 / Compound-Document magic — identifies a binary .xls payload.
    _OLE2_MAGIC = b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"

    def fetch(self) -> list[dict]:
        """
        Prefer the ANSM export endpoint (binary .xls with rich structured
        fields); fall back to CSV, then to HTML table parsing.
        Returns a list of raw record dicts, each tagged with a "source" key.
        """
        # ── Attempt 1: export endpoint ────────────────────────────────────────
        try:
            resp = self._get(self.EXPORT_URL)
            ct = resp.headers.get("content-type", "")
            content = resp.content

            # The export is a binary .xls (OLE2) despite the vnd.ms-excel /
            # filename hints — detect it by magic bytes, not Content-Type.
            if content[:8] == self._OLE2_MAGIC:
                records = self._parse_export_xls(content)
                if records:
                    self.log.info(
                        "ANSM export endpoint used (binary .xls)",
                        extra={"records": len(records), "content_type": ct},
                    )
                    return records
                self.log.warning(
                    "ANSM .xls export parsed to zero rows; falling back to HTML",
                    extra={"content_type": ct},
                )
            elif "csv" in ct or "text/plain" in ct or content[:6].isascii():
                # ANSM could switch to a real CSV in future — handle it too.
                records = self._parse_export_csv(content)
                if records:
                    self.log.info(
                        "ANSM export endpoint used (CSV)",
                        extra={"records": len(records), "content_type": ct},
                    )
                    return records
                self.log.info(
                    "ANSM export returned unparseable text; falling back to HTML",
                    extra={"content_type": ct},
                )
            else:
                self.log.info(
                    "ANSM export format unrecognised; falling back to HTML",
                    extra={"content_type": ct, "head": content[:8].hex()},
                )
        except Exception as exc:
            self.log.info(
                "ANSM export endpoint failed; falling back to HTML",
                extra={"error": str(exc)},
            )

        # ── Attempt 2: HTML listing page ──────────────────────────────────────
        return self._fetch_html()

    # Export column headers (confirmed 2026-06-03). Order is stable but we map
    # by header name, not index, so a column reshuffle won't silently corrupt.
    _XLS_COL_TITRE   = "Titre"
    _XLS_COL_DEBUT   = "Date de début de situation"
    _XLS_COL_REMISE  = "Date de remise à disposition"
    _XLS_COL_STATUT  = "Statut"
    _XLS_COL_PRODUIT = "Produit(s) de santé"
    _XLS_COL_DOMAINE = "Domaine(s) médical(aux)"
    _XLS_COL_URL     = "URL de la page"

    def _parse_export_xls(self, content: bytes) -> list[dict]:
        """
        Parse the binary .xls export into a list of raw record dicts keyed by
        the French column headers.  Returns [] if xlrd is unavailable or the
        sheet is empty, so fetch() can fall back to HTML.
        """
        try:
            import xlrd
        except ImportError:
            self.log.warning(
                "xlrd not installed — cannot parse ANSM .xls export; "
                "falling back to HTML (run: pip install xlrd)"
            )
            return []

        # The export is a slightly non-standard CDF (PhpSpreadsheet output) that
        # trips xlrd's strict directory validation; ignore_workbook_corruption
        # tolerates it and yields clean cell data.
        wb = xlrd.open_workbook(
            file_contents=content, ignore_workbook_corruption=True
        )
        sheet = wb.sheet_by_index(0)
        if sheet.nrows < 2:
            return []

        headers = [str(sheet.cell_value(0, c)).strip() for c in range(sheet.ncols)]
        records: list[dict] = []
        for r in range(1, sheet.nrows):
            row = {
                headers[c]: str(sheet.cell_value(r, c)).strip()
                for c in range(sheet.ncols)
            }
            row["source"] = "xls"
            records.append(row)

        self.log.info("ANSM .xls parse complete", extra={"total": len(records)})
        return records

    def _parse_export_csv(self, content: bytes) -> list[dict]:
        """Parse CSV bytes returned by the export endpoint."""
        for enc in ("utf-8-sig", "utf-8", "latin-1"):
            try:
                text = content.decode(enc)
                break
            except UnicodeDecodeError:
                continue
        else:
            text = content.decode("latin-1", errors="replace")

        reader = csv.DictReader(io.StringIO(text), delimiter=";")
        out: list[dict] = []
        for row in reader:
            rec = {k.strip(): (v.strip() if isinstance(v, str) else v)
                   for k, v in row.items()}
            rec["source"] = "csv"
            out.append(rec)
        return out

    def _fetch_html(self) -> list[dict]:
        """Parse the ANSM HTML listing table."""
        response = self._get(self.LIST_URL)
        soup = BeautifulSoup(response.text, "lxml")

        records: list[dict] = []

        for tr in soup.select("tr[data-href]"):
            cells = tr.find_all("td")
            if not cells:
                continue

            # Confirmed column order (2026-02-22):
            #   cell[0]: Statut (Rupture de stock / Tension / Arrêt …)
            #   cell[1]: Date (DD/MM/YYYY)
            #   cell[2]: Dénomination + INN in [brackets]
            statut       = cells[0].get_text(strip=True) if len(cells) > 0 else ""
            date_raw     = cells[1].get_text(strip=True) if len(cells) > 1 else ""
            denomination = cells[2].get_text(" ", strip=True) if len(cells) > 2 else ""
            detail_slug  = tr.get("data-href", "")

            records.append({
                "denomination":  denomination,
                "statut":        statut,
                "date_raw":      date_raw,
                "detail_slug":   detail_slug,
                "source":        "html",
            })

        self.log.info(
            "ANSM HTML fetch complete",
            extra={"total": len(records)},
        )
        return records

    # ─────────────────────────────────────────────────────────────────────────
    # normalize()
    # ─────────────────────────────────────────────────────────────────────────

    def normalize(self, raw: dict | list) -> list[dict]:
        records = raw if isinstance(raw, list) else []
        self.log.info(
            "Normalising ANSM records",
            extra={"source": self.SOURCE_NAME, "raw_count": len(records)},
        )

        normalised: list[dict] = []
        skipped = 0

        for rec in records:
            try:
                result = self._normalise_record(rec)
                if result is None:
                    skipped += 1
                    continue
                normalised.append(result)
            except Exception as exc:
                skipped += 1
                self.log.warning(
                    "Failed to normalise ANSM record",
                    extra={"error": str(exc), "rec": str(rec)[:200]},
                )

        self.log.info(
            "Normalisation done",
            extra={"total": len(records), "normalised": len(normalised), "skipped": skipped},
        )
        return normalised

    # ─────────────────────────────────────────────────────────────────────────
    # Private helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _normalise_record(self, rec: dict) -> dict | None:
        source = rec.get("source", "html")

        if source == "xls":
            return self._normalise_xls_record(rec)
        if source != "html":
            # CSV export path — map CSV columns dynamically
            return self._normalise_csv_record(rec)

        # ── HTML path ─────────────────────────────────────────────────────────
        denomination = rec.get("denomination", "").strip()
        if not denomination:
            return None

        # Extract INN from bracket notation: "[aztréonam]" → "aztréonam"
        # Try square brackets first (allows nested parens), then round brackets.
        sq_match = self._RE_INN_SQUARE.search(denomination)
        pr_match = self._RE_INN_PARENS.search(denomination)
        if sq_match:
            generic_name = sq_match.group(1).strip()
        elif pr_match:
            generic_name = pr_match.group(1).strip()
        else:
            # Try extracting INN from the end of the detail slug
            slug = rec.get("detail_slug", "")
            generic_name = self._inn_from_slug(slug, denomination)

        if not generic_name:
            return None

        brand_name = self._strip_inn_brackets(denomination).strip(" ,;")
        brand_names = [brand_name] if brand_name and brand_name.lower() != generic_name.lower() else []

        raw_status = rec.get("statut", "").strip()
        status = self._map_status(raw_status)

        slug = rec.get("detail_slug", "")
        source_url = (self.BASE_URL + slug) if slug else self.LIST_URL
        start_date = (self._parse_date(rec.get("date_raw", ""))
                      or datetime.now(timezone.utc).date().isoformat())

        # Map statut to availability and use as reason (best available from HTML)
        avail_map = {"active": "unavailable", "anticipated": "limited", "resolved": "available"}
        availability = avail_map.get(status, None)

        return {
            "generic_name":              generic_name,
            "brand_names":               brand_names,
            "status":                    status,
            "severity":                  "high" if status == "active" else "medium",
            "reason":                    raw_status or None,
            "reason_category":           self._map_reason(raw_status),
            "availability_status":       availability,
            "start_date":                start_date,
            "end_date":                  None,
            "estimated_resolution_date": None,
            "source_url":                source_url,
            "notes":                     denomination if denomination != generic_name else None,
            "raw_record": {
                "denomination": denomination,
                "statut":       raw_status,
                "slug":         slug,
            },
        }

    def _normalise_xls_record(self, rec: dict) -> dict | None:
        """
        Handle records from the binary .xls export (the preferred path).
        Maps the 9 structured columns, uses the stable "Date de début de
        situation" as start_date (dedup-safe) and "Date de remise à
        disposition" as the real end/estimated date, and preserves the full
        French row in raw_record for audit.
        """
        denomination = rec.get(self._XLS_COL_TITRE, "").strip()
        if not denomination:
            return None

        # INN: square brackets → round brackets → slug tail (same as HTML path).
        sq_match = self._RE_INN_SQUARE.search(denomination)
        pr_match = self._RE_INN_PARENS.search(denomination)
        if sq_match:
            generic_name = sq_match.group(1).strip()
        elif pr_match:
            generic_name = pr_match.group(1).strip()
        else:
            generic_name = self._inn_from_slug(rec.get(self._XLS_COL_URL, ""), denomination)
        if not generic_name:
            return None

        brand_name = self._strip_inn_brackets(denomination).strip(" ,;–-")
        brand_names = (
            [brand_name]
            if brand_name and brand_name.lower() != generic_name.lower()
            else []
        )

        raw_status = rec.get(self._XLS_COL_STATUT, "").strip()
        status = self._map_status(raw_status)

        # Stable start date — the whole reason this path is preferred over HTML.
        start_date = (
            self._parse_date(rec.get(self._XLS_COL_DEBUT, ""))
            or datetime.now(timezone.utc).date().isoformat()
        )

        # "Remise à disposition" = restored to supply. Treat as end_date when the
        # situation is resolved, otherwise as an estimated resolution date.
        remise = self._parse_date(rec.get(self._XLS_COL_REMISE, ""))
        end_date = remise if status == "resolved" else None
        estimated = remise if status != "resolved" else None

        source_url = rec.get(self._XLS_COL_URL, "").strip() or self.LIST_URL
        domaine = rec.get(self._XLS_COL_DOMAINE, "").strip()
        produit = rec.get(self._XLS_COL_PRODUIT, "").strip()

        avail_map = {"active": "unavailable", "anticipated": "limited", "resolved": "available"}
        availability = avail_map.get(status)

        # Notes carry the human-readable French denomination + therapeutic area;
        # the full untouched row is in raw_record for audit.
        notes_parts = [denomination]
        if domaine:
            notes_parts.append(f"Domaine: {domaine}")
        if produit and produit != "Médicaments":
            notes_parts.append(f"Type: {produit}")

        return {
            "generic_name":              generic_name,
            "brand_names":               brand_names,
            "status":                    status,
            "severity":                  "high" if status == "active" else "medium",
            "reason":                    raw_status or None,
            "reason_category":           self._map_reason(raw_status),
            "availability_status":       availability,
            "start_date":                start_date,
            "end_date":                  end_date,
            "estimated_resolution_date": estimated,
            "source_url":                source_url,
            "notes":                     "\n".join(notes_parts),
            "raw_record":                rec,
        }

    def _normalise_csv_record(self, rec: dict) -> dict | None:
        """Handle records from the CSV export endpoint."""
        keys_lower = {k.lower(): k for k in rec}

        def get(*names: str) -> str:
            for n in names:
                orig = keys_lower.get(n.lower())
                if orig and rec.get(orig):
                    return str(rec[orig]).strip()
            return ""

        # DCI = Dénomination commune internationale = INN
        generic_name = (
            get("dci", "dénomination commune internationale",
                "denomination commune internationale", "principio activo",
                "inn", "substance active")
            or get("dénomination", "denomination", "medicament", "médicament")
        )
        if not generic_name:
            return None

        denomination = get("dénomination", "denomination", "spécialité", "specialite") or generic_name
        brand_names = ([denomination] if denomination and denomination.lower() != generic_name.lower()
                       else [])

        raw_status = get("statut", "status", "état", "etat")
        status = self._map_status(raw_status)

        start_date = (self._parse_date(get("date de début", "date debut", "date de signalement"))
                      or datetime.now(timezone.utc).date().isoformat())
        end_date = self._parse_date(get("date de fin prévue", "date fin", "date de fin"))
        estimated = end_date if status != "resolved" else None
        end_date = end_date if status == "resolved" else None

        raw_reason = get("cause", "cause déclarée", "cause declaree", "motif")
        reason_category = self._map_reason(raw_reason)

        lab = get("laboratoire", "titulaire", "fabricant")
        notes_parts: list[str] = []
        if lab:
            notes_parts.append(f"Lab: {lab}")
        if raw_reason:
            notes_parts.append(raw_reason)

        return {
            "generic_name":              generic_name,
            "brand_names":               brand_names,
            "status":                    status,
            "severity":                  "high" if status == "active" else "medium",
            "reason":                    raw_reason or None,
            "reason_category":           reason_category,
            "start_date":                start_date,
            "end_date":                  end_date,
            "estimated_resolution_date": estimated,
            "source_url":                self.LIST_URL,
            "notes":                     "\n".join(notes_parts) or None,
            "raw_record":                rec,
        }

    def _map_status(self, raw: str) -> str:
        lower = raw.lower().strip()
        # Normalise French accented characters for matching
        lower = (lower.replace("é", "e").replace("è", "e").replace("ê", "e")
                      .replace("â", "a").replace("à", "a").replace("î", "i"))
        for key, val in self._STATUS_MAP.items():
            norm_key = (key.replace("é", "e").replace("è", "e").replace("ê", "e")
                           .replace("â", "a").replace("à", "a").replace("î", "i")
                           .replace("'", "'"))
            if norm_key in lower:
                return val
        return "active"

    def _map_reason(self, raw: str) -> str:
        if not raw:
            return "unknown"
        lower = raw.lower()
        for key, cat in self._REASON_MAP.items():
            norm = key.replace("é", "e").replace("è", "e").replace("ê", "e")
            if norm in lower or key in lower:
                return cat
        return "unknown"

    @staticmethod
    def _strip_inn_brackets(name: str) -> str:
        """Remove bracket / parenthesis INN annotations from brand name."""
        # Strip square-bracket sections (may contain nested parens) first
        cleaned = re.sub(r'\s*\[[^\]]+\]', "", name).strip()
        # Then strip any remaining round-bracket INN annotations
        cleaned = re.sub(r'\s*\([a-zàâäéèêëîïôùûü /,\-]+\)', "", cleaned, flags=re.IGNORECASE).strip()
        return cleaned

    @staticmethod
    def _inn_from_slug(slug: str, fallback: str) -> str:
        """
        Attempt to extract INN from the end of an ANSM URL slug.
        Pattern: /disponibilites-des-produits-de-sante/medicaments/{brand}-...-{inn}
        The INN typically appears as the last hyphenated segment(s).
        """
        if not slug:
            return fallback
        path = slug.rstrip("/").split("/")[-1]  # last path segment
        parts = path.split("-")
        # Filter out numeric tokens, dosage units, and very common French words
        STOP = {"de", "du", "la", "le", "les", "et", "en", "a", "au", "aux",
                "pour", "par", "sur", "avec", "sans", "ml", "mg", "g", "mcg",
                "comprime", "comprimes", "gelule", "gelules", "solution",
                "injectable", "poudre", "suspension", "capsule", "capsules",
                "infusion", "perfusion", "boite", "flacon"}
        drug_parts = [p for p in parts if p.isalpha() and p not in STOP and len(p) > 2]
        # The last meaningful part is likely the INN
        if drug_parts:
            return drug_parts[-1]
        return fallback

    @staticmethod
    def _parse_date(raw: str | None) -> str | None:
        if not raw or not str(raw).strip():
            return None
        try:
            dt = dtparser.parse(str(raw).strip(), dayfirst=True)
            return dt.date().isoformat()
        except (ValueError, OverflowError):
            return None


# ─────────────────────────────────────────────────────────────────────────────
# Standalone entrypoint
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import json
    import os
    import sys

    from dotenv import load_dotenv

    load_dotenv()
    dry_run = os.environ.get("MEDERTI_DRY_RUN", "0").strip() == "1"

    if dry_run:
        from unittest.mock import MagicMock
        from collections import Counter

        print("=" * 60)
        print("DRY RUN MODE  (MEDERTI_DRY_RUN=1)")
        print("=" * 60)

        scraper = ANSMScraper(db_client=MagicMock())
        raw = scraper.fetch()
        print(f"── Raw records received : {len(raw)}")

        events = scraper.normalize(raw)
        print(f"── Normalised events    : {len(events)}")

        if events:
            for e in events[:3]:
                sample = {k: v for k, v in e.items() if k != "raw_record"}
                print(json.dumps(sample, indent=2, default=str))

            print("\n── Status breakdown:")
            for k, v in sorted(Counter(e["status"] for e in events).items()):
                print(f"   {k:25s} {v}")

        print("\n── Dry run complete.")
        sys.exit(0)

    print("=" * 60)
    print("LIVE RUN — writing to Supabase")
    print("=" * 60)
    scraper = ANSMScraper()
    summary = scraper.run()
    print(json.dumps(summary, indent=2, default=str))
    sys.exit(0 if summary["status"] in ("success", "duplicate") else 1)
