"""
INVIMA Colombia — Listado de Abastecimiento y Desabastecimiento de Medicamentos
--------------------------------------------------------------------------------
Source:  INVIMA (Instituto Nacional de Vigilancia de Medicamentos y Alimentos)
URL:     https://www.invima.gov.co/productos-vigilados/medicamentos-y-productos-biologicos/desabastecimientos

INVIMA publishes a monthly PDF listing every active ingredient / product under
shortage surveillance, with an explicit Spanish-language status taxonomy:

    "En monitorización"              — being monitored (early tier; not yet
                                        confirmed at-risk or out of stock)
    "En riesgo de desabastecimiento" — at risk of shortage
    "Desabastecido" (+ *,**,***,**** footnote markers referencing endnotes)
                                      — currently out of stock
    "No desabastecido"               — no longer in shortage (resolved)
    "Descontinuado"                  — permanently discontinued by the MAH
    "No comercializado"              — never actually marketed / withdrawn

This is one of the few genuinely structured, tabular shortage feeds we've
found in Latin America (verified live 2026-07-02 against the Enero 2026
report, 91 pages / ~770 tracked line items).

Landing page quirk: older monthly reports link straight to a `.pdf` on
invima.gov.co; newer ones (~2025 onward) link to an internal `/biblioteca/...`
document page that itself contains a `/biblioteca/download/<id>` link to the
actual PDF. fetch() follows both link shapes.

PDF table quirk #1: pdfplumber's table extraction repeats the section title
as row 0 of every page's table, and repeats the column header row
("No.", "Nombre del Medicamento", "ATC", ...) at the top of each page. A
single tracked product can span multiple physical table rows when several
manufacturers report separately (subsequent rows leave No./Nombre/Estado
blank) — normalize() forward-fills those columns from the last fully
populated row.

PDF table quirk #2 (verified live 2026-07-02 — the Mayo 2026 report,
generated by a different pipeline than earlier months): pdfplumber's
default `page.extract_tables()` returns badly scrambled/interleaved text in
this report — its geometric word-ordering heuristic misorders characters
that the PDF itself draws in a different visual arrangement. The literal
content-stream draw order IS correct reading order for this document.
Fix: use `page.find_tables()` for cell geometry only, then re-extract each
cell's text ourselves via `page.crop(bbox).extract_text(use_text_flow=True)`
— this reads characters in content-stream order instead of re-sorting by
position, and produces clean text on both the well-behaved (Enero 2026) and
the previously-garbled (Mayo 2026) reports alike.

Data source UUID:  10000000-0000-0000-0000-000000000108
Country:           Colombia
Country code:      CO
Confidence:        85/100 (seeded in migration 064)

Cron:  Not yet wired — integrated separately per project convention.
"""

from __future__ import annotations

import io
import re
from datetime import date, datetime, timezone
from typing import Any

from backend.scrapers.base_scraper import BaseScraper, ScraperError
from backend.utils.reason_mapper import map_reason_category


class ColombiaINVIMAScraper(BaseScraper):
    SOURCE_ID: str    = "10000000-0000-0000-0000-000000000108"
    SOURCE_NAME: str  = "INVIMA — Desabastecimiento de medicamentos (Colombia)"
    BASE_URL: str     = "https://www.invima.gov.co/productos-vigilados/medicamentos-y-productos-biologicos/desabastecimientos"
    COUNTRY: str      = "Colombia"
    COUNTRY_CODE: str = "CO"

    RATE_LIMIT_DELAY: float = 3.0   # Be polite to the Colombian gov server
    REQUEST_TIMEOUT: float  = 90.0  # Monthly PDFs run 90+ pages
    SCRAPER_VERSION: str    = "1.0.0"

    # INVIMA's explicit Spanish status taxonomy -> our canonical status.
    # Matched via substring after stripping footnote markers/whitespace, so
    # "Desabastecido **" / "Desabastecido*" etc. all map the same way.
    _STATUS_MAP: list[tuple[str, str]] = [
        ("en riesgo de desabastecimiento", "anticipated"),
        ("en monitorizacion",              "anticipated"),
        ("desabastecido",                  "active"),
        ("no desabastecido",               "resolved"),
        ("no comercializado",              "resolved"),
        ("descontinuado",                  "resolved"),
    ]

    # Column order in INVIMA's monthly table (verified live against the
    # Enero 2026 report). If INVIMA reorders columns this needs revisiting —
    # normalize() also sanity-checks the header row where present.
    _COL_NO      = 0
    _COL_NOMBRE  = 1
    _COL_ATC     = 2
    _COL_INICIO  = 3
    _COL_ULTIMO  = 4
    _COL_ESTADO  = 5
    _COL_CAUSAS  = 6

    # -------------------------------------------------------------------------
    # fetch()
    # -------------------------------------------------------------------------

    def fetch(self) -> list[dict]:
        """
        Fetch the INVIMA monthly shortage/supply-monitoring list.

        Strategy:
        1. GET the desabastecimientos landing page.
        2. Find links to monthly reports — either direct .pdf links, or
           internal /biblioteca/<slug> document pages that need a follow-up
           fetch to resolve the actual /biblioteca/download/<id> PDF URL.
        3. Download and parse the most recent report(s) with pdfplumber
           (table extraction first, per-page text fallback).
        4. Return raw table rows (with month_year + pdf_url attached).
        """
        from bs4 import BeautifulSoup

        self.log.info("Scrape started", extra={
            "source": self.SOURCE_NAME,
            "url": self.BASE_URL,
        })

        resp = self._get(self.BASE_URL)
        soup = BeautifulSoup(resp.text, "html.parser")

        pdf_links = self._find_pdf_links(soup)
        self.log.info(
            "Found candidate report links on page",
            extra={"count": len(pdf_links)},
        )

        if not pdf_links:
            self.log.warning("No INVIMA shortage report links found on landing page")
            return []

        # Only the most recent report is needed — INVIMA republishes a full
        # cumulative list every month, so older reports are strict subsets/
        # historical snapshots of the same tracked products.
        records: list[dict] = []
        for link_info in pdf_links[:1]:
            try:
                pdf_url = self._resolve_pdf_url(link_info)
                if not pdf_url:
                    continue
                link_info["url"] = pdf_url
                pdf_records = self._fetch_and_parse_pdf(link_info)
                records.extend(pdf_records)
            except Exception as exc:
                self.log.warning(
                    "Failed to fetch/parse INVIMA report",
                    extra={"url": link_info.get("url", ""), "error": str(exc)},
                )

        self.log.info("INVIMA fetch complete", extra={"records": len(records)})
        return records

    def _find_pdf_links(self, soup) -> list[dict]:
        """Find links to monthly shortage report documents on the landing page.

        Two shapes seen live:
          - direct https://.../attachments/.../<name>.pdf
          - internal /biblioteca/<slug> pages (need a follow-up fetch)
        Both are filtered to the "desabastecimiento" report family and
        excluded from one-off circulars/annual summaries.
        """
        candidates: list[dict] = []
        seen_urls: set[str] = set()

        for link in soup.select("a[href]"):
            href = (link.get("href") or "").strip()
            if not href:
                continue
            title = link.get_text(strip=True)
            title_lower = title.lower()

            is_pdf_link = href.lower().endswith(".pdf")
            is_biblioteca_link = "/biblioteca/" in href and not href.lower().endswith(".pdf")

            if not (is_pdf_link or is_biblioteca_link):
                continue

            # Only the recurring monthly "listado de abastecimiento y
            # desabastecimiento" report — skip circulars, annual reports,
            # and one-off ad-hoc availability studies.
            if "listado" not in title_lower and "listado" not in href.lower():
                continue

            if href.startswith("/"):
                href = f"https://www.invima.gov.co{href}"
            elif not href.startswith("http"):
                href = f"https://www.invima.gov.co/{href}"

            if href in seen_urls:
                continue
            seen_urls.add(href)

            month_year = self._extract_month_year(title) or self._extract_month_year(href)

            candidates.append({
                "url": href,
                "title": title,
                "month_year": month_year,
                "is_biblioteca_page": is_biblioteca_link,
            })

        candidates.sort(key=lambda x: x.get("month_year") or "", reverse=True)
        return candidates

    def _resolve_pdf_url(self, link_info: dict) -> str | None:
        """For /biblioteca/<slug> document pages, follow through to the
        actual /biblioteca/download/<id> PDF link. Direct .pdf links pass
        through unchanged."""
        if not link_info.get("is_biblioteca_page"):
            return link_info["url"]

        from bs4 import BeautifulSoup

        self.log.info("Resolving biblioteca document page", extra={"url": link_info["url"]})
        resp = self._get(link_info["url"])
        soup = BeautifulSoup(resp.text, "html.parser")

        for link in soup.select("a[href]"):
            href = (link.get("href") or "").strip()
            if "/biblioteca/download/" in href:
                if href.startswith("/"):
                    href = f"https://www.invima.gov.co{href}"
                return href

        self.log.warning(
            "Could not find download link on biblioteca page",
            extra={"url": link_info["url"]},
        )
        return None

    def _extract_month_year(self, text: str) -> str | None:
        """Extract a 'YYYY-MM' month reference from Spanish month names."""
        months = {
            "enero": "01", "febrero": "02", "marzo": "03", "abril": "04",
            "mayo": "05", "junio": "06", "julio": "07", "agosto": "08",
            "septiembre": "09", "setiembre": "09", "octubre": "10",
            "noviembre": "11", "diciembre": "12",
        }
        text_lower = text.lower()
        for month_name, month_num in months.items():
            if month_name in text_lower:
                year_match = re.search(r"(20\d{2})", text)
                if year_match:
                    return f"{year_match.group(1)}-{month_num}"
        return None

    def _fetch_and_parse_pdf(self, pdf_info: dict) -> list[dict]:
        """Download the INVIMA monthly PDF and extract table rows from it."""
        try:
            import pdfplumber
        except ImportError:
            self.log.error(
                "pdfplumber not installed — required for INVIMA PDF parsing. "
                "Install with: pip install pdfplumber"
            )
            return []

        url = pdf_info["url"]
        self.log.info("Downloading PDF", extra={"url": url})

        resp = self._get(url)

        records: list[dict] = []
        with pdfplumber.open(io.BytesIO(resp.content)) as pdf:
            self.log.info("PDF opened", extra={"pages": len(pdf.pages), "url": url})

            for page_num, page in enumerate(pdf.pages, start=1):
                try:
                    tables = self._extract_tables_text_flow(page)
                    if tables:
                        for table in tables:
                            page_records = self._parse_table(table, pdf_info, page_num)
                            records.extend(page_records)
                    else:
                        text = page.extract_text(use_text_flow=True)
                        if text:
                            records.extend(self._parse_text(text, pdf_info, page_num))
                except Exception as exc:
                    self.log.warning(
                        "Failed to parse PDF page",
                        extra={"url": url, "page": page_num, "error": str(exc)},
                    )

        self.log.info("PDF parsing complete", extra={"url": url, "records": len(records)})
        return records

    @staticmethod
    def _extract_tables_text_flow(page) -> list[list[list[str]]]:
        """Extract tables from a page, re-reading each cell's text in
        content-stream order (use_text_flow=True) rather than pdfplumber's
        default geometric word-sort. See module docstring "PDF table quirk
        #2" — some INVIMA monthly reports scramble text under the default
        extraction but read correctly with use_text_flow. Cell *geometry*
        (row/column boundaries) still comes from find_tables(); only the
        per-cell text re-extraction differs from the base-class pattern
        used elsewhere (e.g. india_cdsco_scraper's page.extract_tables()).
        """
        tables_out: list[list[list[str]]] = []
        for table in page.find_tables():
            rows_out: list[list[str]] = []
            for row in table.rows:
                cell_texts: list[str] = []
                for bbox in row.cells:
                    if bbox is None:
                        cell_texts.append("")
                        continue
                    cropped = page.crop(bbox)
                    text = cropped.extract_text(use_text_flow=True) or ""
                    cell_texts.append(text.strip())
                rows_out.append(cell_texts)
            tables_out.append(rows_out)
        return tables_out

    def _parse_table(self, table: list[list], pdf_info: dict, page_num: int) -> list[dict]:
        """Parse one page's table, forward-filling No./Nombre/ATC/fechas/Estado
        across continuation rows (multiple manufacturer entries under one
        tracked product leave those columns blank on subsequent rows)."""
        records: list[dict] = []
        if not table:
            return records

        last: dict[str, str] = {}

        for row in table:
            if not row or len(row) <= self._COL_CAUSAS:
                continue

            cells = [str(c or "").strip() for c in row]
            c0 = cells[self._COL_NO]

            # Skip section-title rows (repeated per page) and repeated
            # column-header rows.
            if "MEDICAMENTOS CON PRINCIPIOS" in cells[0].upper():
                continue
            if c0 in ("No.", "No") or cells[self._COL_NOMBRE].lower() == "nombre del medicamento":
                continue
            if not any(cells):
                continue

            is_new_record = c0.isdigit()

            if is_new_record:
                last = {
                    "no":        c0,
                    "nombre":    cells[self._COL_NOMBRE],
                    "atc":       cells[self._COL_ATC],
                    "inicio":    cells[self._COL_INICIO],
                    "ultimo":    cells[self._COL_ULTIMO],
                    "estado":    cells[self._COL_ESTADO],
                    "causas":    cells[self._COL_CAUSAS],
                }
            elif last:
                # Continuation row (extra manufacturer detail) — fill any
                # columns that carry new non-blank content, keep the rest.
                if cells[self._COL_ATC]:
                    last["atc"] = last["atc"] or cells[self._COL_ATC]
                if cells[self._COL_INICIO]:
                    last["inicio"] = last["inicio"] or cells[self._COL_INICIO]
                if cells[self._COL_ESTADO]:
                    last["estado"] = last["estado"] or cells[self._COL_ESTADO]
                if cells[self._COL_CAUSAS]:
                    last["causas"] = (last["causas"] + " " + cells[self._COL_CAUSAS]).strip()
            else:
                continue

            if not last.get("nombre") or not last.get("estado"):
                # Continuation rows before we've ever seen a full record, or
                # rows still missing the fields we need — nothing to emit yet.
                continue

            records.append({
                "no":           last["no"],
                "nombre":       last["nombre"],
                "atc":          last["atc"],
                "fecha_inicio": last["inicio"],
                "fecha_ultimo": last["ultimo"],
                "estado":       last["estado"],
                "causas":       last["causas"],
                "pdf_url":      pdf_info["url"],
                "pdf_title":    pdf_info.get("title", ""),
                "month_year":   pdf_info.get("month_year", ""),
                "page_num":     page_num,
                "source":       "table",
            })

        return records

    def _parse_text(self, text: str, pdf_info: dict, page_num: int) -> list[dict]:
        """Fallback free-text parser for pages where table extraction fails
        (e.g. a malformed page or a scanned/degraded PDF). Best-effort only —
        looks for "<status keyword>" lines near a drug-name-looking line."""
        records: list[dict] = []
        status_keywords = [
            "en riesgo de desabastecimiento", "en monitorización",
            "desabastecido", "no desabastecido", "no comercializado",
            "descontinuado",
        ]

        lines = [ln.strip() for ln in text.split("\n") if ln.strip()]
        for i, line in enumerate(lines):
            line_lower = line.lower()
            matched_status = next((kw for kw in status_keywords if kw in line_lower), None)
            if not matched_status:
                continue
            # Look back a few lines for something that looks like a drug name
            # (all-caps, letters, reasonably long).
            drug_name = None
            for back in range(1, 6):
                idx = i - back
                if idx < 0:
                    break
                candidate = lines[idx]
                if len(candidate) >= 3 and candidate.upper() == candidate and re.search(r"[A-ZÁÉÍÓÚÑ]{3,}", candidate):
                    drug_name = candidate
                    break
            if not drug_name:
                continue

            records.append({
                "no": "",
                "nombre": drug_name,
                "atc": "",
                "fecha_inicio": "",
                "fecha_ultimo": "",
                "estado": matched_status,
                "causas": "",
                "pdf_url": pdf_info["url"],
                "pdf_title": pdf_info.get("title", ""),
                "month_year": pdf_info.get("month_year", ""),
                "page_num": page_num,
                "source": "text",
            })

        return records

    # -------------------------------------------------------------------------
    # normalize()
    # -------------------------------------------------------------------------

    def normalize(self, raw: list[dict]) -> list[dict]:
        """Normalize INVIMA records into standard shortage event dicts."""
        self.log.info(
            "Normalising INVIMA records",
            extra={"source": self.SOURCE_NAME, "raw_count": len(raw)},
        )

        normalised: list[dict] = []
        skipped = 0
        today = date.today().isoformat()

        for rec in raw:
            try:
                result = self._normalise_record(rec, today)
                if result is None:
                    skipped += 1
                    continue
                normalised.append(result)
            except Exception as exc:
                skipped += 1
                self.log.warning(
                    "Failed to normalise INVIMA record",
                    extra={"error": str(exc), "rec": str(rec)[:200]},
                )

        self.log.info(
            "Normalisation done",
            extra={"total": len(raw), "normalised": len(normalised), "skipped": skipped},
        )
        return normalised

    def _normalise_record(self, rec: dict, today: str) -> dict | None:
        """Convert a single INVIMA table row into a normalised shortage event dict."""
        raw_nombre = str(rec.get("nombre") or "").strip()
        if not raw_nombre:
            return None

        generic_name = self._clean_drug_name(raw_nombre)
        if not generic_name:
            return None

        raw_estado = str(rec.get("estado") or "").strip()
        status = self._map_status(raw_estado)
        if status is None:
            # Unrecognised status label — surface it via warning rather than
            # silently dropping the row so taxonomy drift gets noticed.
            self.log.warning(
                "Unrecognised INVIMA estado — skipping",
                extra={"estado": raw_estado, "nombre": raw_nombre},
            )
            return None

        raw_causas = str(rec.get("causas") or "").strip()
        # INVIMA uses a literal "---" placeholder for "no cause reported" —
        # treat it the same as blank rather than storing it as a reason.
        if raw_causas in ("---", "-", "--"):
            raw_causas = ""
        reason_category = map_reason_category(raw_causas)
        if reason_category == "unknown":
            if "descontinuado" in raw_estado.lower() or "no comercializado" in raw_estado.lower():
                reason_category = "discontinuation"
            elif not raw_causas:
                reason_category = "unknown"

        start_date = (
            self._parse_date(rec.get("fecha_inicio"))
            or self._parse_month_year_date(rec.get("month_year"))
            or today
        )
        last_seguimiento = self._parse_date(rec.get("fecha_ultimo"))

        # Severity: a confirmed stock-out outranks an at-risk/monitored entry.
        if status == "active":
            severity = "high"
        elif status == "anticipated":
            severity = "medium"
        else:
            severity = "low"

        notes_parts: list[str] = []
        atc = str(rec.get("atc") or "").strip()
        if atc:
            notes_parts.append(f"ATC: {atc}")
        if last_seguimiento:
            notes_parts.append(f"Último seguimiento: {last_seguimiento}")
        pdf_title = str(rec.get("pdf_title") or "").strip()
        if pdf_title:
            notes_parts.append(f"Report: {pdf_title}")
        if raw_estado:
            notes_parts.append(f"Estado INVIMA: {raw_estado.replace(chr(10), ' ')}")
        notes = "; ".join(notes_parts) or None

        source_url = rec.get("pdf_url") or self.BASE_URL

        return {
            "generic_name":            generic_name.title(),
            "brand_names":             [],
            "status":                  status,
            "severity":                severity,
            "reason":                  raw_causas.replace("\n", " ").strip() or None,
            "reason_category":         reason_category,
            "start_date":              start_date,
            "source_url":              source_url,
            "notes":                   notes,
            "source_confidence_score": 85,
            "raw_record":              rec,
        }

    # -------------------------------------------------------------------------
    # Private helpers
    # -------------------------------------------------------------------------

    def _map_status(self, raw_estado: str) -> str | None:
        """Map INVIMA's Spanish status taxonomy to our canonical status.
        Strips footnote asterisks and normalises accents/case before matching."""
        if not raw_estado:
            return None
        normalised = self._strip_accents(raw_estado).lower()
        normalised = re.sub(r"\*+", "", normalised)
        normalised = re.sub(r"\s+", " ", normalised).strip()
        for keyword, status in self._STATUS_MAP:
            if keyword in normalised:
                return status
        return None

    @staticmethod
    def _strip_accents(text: str) -> str:
        import unicodedata
        nfkd = unicodedata.normalize("NFKD", text)
        return "".join(c for c in nfkd if not unicodedata.combining(c))

    @staticmethod
    def _clean_drug_name(name: str) -> str:
        """
        Clean a drug name from INVIMA's "Nombre del Medicamento" cell.

        These cells often stack the generic name, dosage form, and strength
        on separate lines within the same cell, and sometimes list a second
        related product (e.g. an injectable + a tablet form of the same INN)
        — we keep only the first line/product.

        Examples:
            "CLEMASTINA\\nSOLUCIÓN INYECTABLE\\n2 mg / 2 ml" -> "Clemastina"
            "METILERGOMETRINA\\nSOLUCIÓN INYECTABLE\\n0,2 mg / 1 ml (Vial)\\n
             METILERGOMETRINA\\nTABLETA\\n0,2 mg" -> "Metilergometrina"
        """
        if not name:
            return name

        first_line = name.split("\n")[0].strip()

        # Remove trailing dosage-form/strength fragments that sometimes
        # leak onto the first line itself.
        first_line = re.split(
            r"\s+(?:SOLUCIÓN|SOLUCION|TABLETA|CÁPSULA|CAPSULA|EMULSIÓN|"
            r"EMULSION|JARABE|SUSPENSIÓN|SUSPENSION|CREMA|UNGÜENTO|GOTAS?|"
            r"INHALADOR|POLVO|GEL|INYECTABLE|OFTÁLMIC[OA]|NASAL)\b",
            first_line,
            maxsplit=1,
            flags=re.IGNORECASE,
        )[0].strip()

        first_line = re.sub(
            r"\s+\d+[.,]?\d*\s*(?:mg|g|ml|mcg|ui|iu|%|µg|mg/ml|mg/l).*$",
            "",
            first_line,
            flags=re.IGNORECASE,
        ).strip()

        # Strip trailing punctuation left over from splitting.
        first_line = first_line.strip(" -,;")

        return first_line if len(first_line) >= 3 else ""

    @staticmethod
    def _parse_month_year_date(month_year: str | None) -> str | None:
        """Convert a 'YYYY-MM' string to the first day of that month as ISO date."""
        if not month_year:
            return None
        match = re.match(r"^(\d{4})-(\d{2})$", month_year)
        if match:
            return f"{match.group(1)}-{match.group(2)}-01"
        return None

    @staticmethod
    def _parse_date(raw: Any) -> str | None:
        """Parse INVIMA's DD/MM/YYYY date format (day-first) to ISO-8601."""
        if raw is None:
            return None
        if isinstance(raw, datetime):
            return raw.date().isoformat()
        if isinstance(raw, date):
            return raw.isoformat()
        raw_str = str(raw).strip()
        if not raw_str or raw_str in ("-", "N/A", "null", "None", "---"):
            return None
        try:
            from dateutil import parser as dtparser
            dt = dtparser.parse(raw_str, dayfirst=True)
            return dt.date().isoformat()
        except (ValueError, OverflowError, ImportError):
            pass
        return None


# -------------------------------------------------------------------------
# Standalone entrypoint
# -------------------------------------------------------------------------

if __name__ == "__main__":
    import json
    import os
    import sys

    from dotenv import load_dotenv

    load_dotenv()

    dry_run = os.environ.get("MEDERTI_DRY_RUN", "0").strip() == "1"

    if dry_run:
        from unittest.mock import MagicMock

        print("=" * 60)
        print("DRY RUN MODE  (MEDERTI_DRY_RUN=1)")
        print("Fetches live INVIMA data but makes NO database writes.")
        print("Set MEDERTI_DRY_RUN=0 to run against Supabase.")
        print("=" * 60)

        scraper = ColombiaINVIMAScraper(db_client=MagicMock())

        print("\n-- Fetching from INVIMA ...")
        raw = scraper.fetch()
        print(f"-- Raw records received : {len(raw)}")

        print("-- Normalising records ...")
        events = scraper.normalize(raw)
        print(f"-- Normalised events    : {len(events)}")

        if events:
            print("\n-- Sample event (first record, raw_record omitted):")
            sample = {k: v for k, v in events[0].items() if k != "raw_record"}
            print(json.dumps(sample, indent=2, default=str, ensure_ascii=False))

            from collections import Counter

            status_counts   = Counter(e["status"] for e in events)
            severity_counts = Counter(e.get("severity") for e in events)
            reason_counts   = Counter(e.get("reason_category") for e in events)

            print("\n-- Status breakdown:")
            for k, v in sorted(status_counts.items()):
                print(f"   {k:25s} {v}")
            print("\n-- Severity breakdown:")
            for k, v in sorted(severity_counts.items()):
                print(f"   {str(k):12s} {v}")
            print("\n-- Reason category breakdown:")
            for k, v in sorted(reason_counts.items()):
                print(f"   {str(k):30s} {v}")

        print("\n-- Dry run complete. No writes made to Supabase.")
        sys.exit(0)

    # -- Live run --
    print("=" * 60)
    print("LIVE RUN - writing to Supabase")
    print("=" * 60)

    scraper = ColombiaINVIMAScraper()
    summary = scraper.run()

    print("\n-- Scrape summary:")
    print(json.dumps(summary, indent=2, default=str))

    sys.exit(0 if summary["status"] in ("success", "duplicate") else 1)
